Codemagic configuration for Android.

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,81 +1,81 @@
 workflows:
-#    react-native-android:
-#        working_directory: apps/Kogito
-#        name: React Native Android
-#        max_build_duration: 120
-#        instance_type: mac_mini_m1
-#        environment:
-##          android_signing:
-##            - keystore_reference
-#          groups:
-#             - devel
-#             - google_credentials # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
-#          vars:
-#            PACKAGE_NAME: "cz.nudz.kogito" # <-- Put your package name here e.g. com.domain.myapp
-#          node: v16.11.1
-#        scripts:
-#            - name: Install npm dependencies
-#              script: |
-#                npm install
-##            - name: Set Android SDK location
-##              script: |
-##                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
-#            - name: Generate keystore file
-#              script: |
-#                echo $KEYSTORE_CONTENT | base64 --decode > android/app/key.jks
-#            - name: Build Android release
-#              script: |
-#                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-#                if [ -z LATEST_BUILD_NUMBER ]; then
-#                  # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-#                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-#                else
-#                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-#                fi
-#                echo "UPDATED_BUILD_NUMBER is $UPDATED_BUILD_NUMBER"
-#
-#                cd android
-#                ./gradlew bundleRelease \
-#                  -PversionCode=$UPDATED_BUILD_NUMBER \
-#                  -PversionName=1.0.$UPDATED_BUILD_NUMBER
-#        artifacts:
-#             - android/app/build/outputs/**/*.aab
-#        publishing:
-#          email:
-#            recipients:
-#              - martin.ladecky@gmail.com
-#            notify:
-#              success: true     # To not receive a notification when a build succeeds
-#              failure: true    # To not receive a notification when a build fails
-#          google_play:
-#            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-#            track: internal   # Any default or custom track that is not in ‘draft’ status
-    react-native-ios:
+    react-native-android:
         working_directory: apps/Kogito
-        name: React Native iOS
+        name: React Native Android
         max_build_duration: 120
         instance_type: mac_mini_m1
-#        integrations:
-#          app_store_connect: codemagic
         environment:
-#          ios_signing:
-#            distribution_type: app_store
-#            bundle_identifier: cz.nudz.kogito
+#          android_signing:
+#            - keystore_reference
+          groups:
+             - devel
+             - google_credentials # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
           vars:
-#            XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Put the name of your Xcode workspace here
-#            XCODE_SCHEME: "CodemagicSample" # <-- Put the name of your Xcode scheme here
-#            APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
-            node: v16.11.1
-            xcode: latest
-            cocoapods: 1.11.2
+            PACKAGE_NAME: "cz.nudz.kogito" # <-- Put your package name here e.g. com.domain.myapp
+          node: v16.11.1
         scripts:
             - name: Install npm dependencies
               script: |
                 npm install
-            - name: Install CocoaPods dependencies
+#            - name: Set Android SDK location
+#              script: |
+#                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+            - name: Generate keystore file
               script: |
-                cd ios && pod update RCT-Folly --no-repo-update && pod install
-#            - name: Set Info.plist values
+                echo $KEYSTORE_CONTENT | base64 --decode > android/app/key.jks
+            - name: Build Android release
+              script: |
+                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+                if [ -z LATEST_BUILD_NUMBER ]; then
+                  # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+                else
+                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                fi
+                echo "UPDATED_BUILD_NUMBER is $UPDATED_BUILD_NUMBER"
+
+                cd android
+                ./gradlew bundleRelease \
+                  -PversionCode=$UPDATED_BUILD_NUMBER \
+                  -PversionName=1.0.$UPDATED_BUILD_NUMBER
+        artifacts:
+             - android/app/build/outputs/**/*.aab
+        publishing:
+          email:
+            recipients:
+              - martin.ladecky@gmail.com
+            notify:
+              success: true     # To not receive a notification when a build succeeds
+              failure: true    # To not receive a notification when a build fails
+          google_play:
+            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+            track: internal   # Any default or custom track that is not in ‘draft’ status
+#    react-native-ios:
+#        working_directory: apps/Kogito
+#        name: React Native iOS
+#        max_build_duration: 120
+#        instance_type: mac_mini_m1
+#        integrations:
+#          app_store_connect: codemagic
+#        environment:
+#          ios_signing:
+#            distribution_type: app_store
+#            bundle_identifier: cz.nudz.kogito
+#          vars:
+#            XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Put the name of your Xcode workspace here
+#            XCODE_SCHEME: "CodemagicSample" # <-- Put the name of your Xcode scheme here
+#            APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
+#            node: v16.11.1
+#            xcode: latest
+#            cocoapods: 1.11.2
+#        scripts:
+#            - name: Install npm dependencies
+#              script: |
+#                npm install
+#            - name: Install CocoaPods dependencies
+#              script: |
+#                cd ios && pod update RCT-Folly --no-repo-update && pod install
+##            - name: Set Info.plist values
 #              script: |
 #                # This allows publishing without manually answering the question about encryption
 #                PLIST=$CM_BUILD_DIR/$XCODE_SCHEME/Info.plist
